using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using System.IO;


namespace learningprojectserver.Services
{
    public class PdfService
    {
        public byte[] GenerateStudentReport()
        {
            // 1. Create document
            Document document = new Document();
            document.Info.Title = "Student Report";

            // 2. Add section
            Section section = document.AddSection();

            // 3. Title
            Paragraph title = section.AddParagraph("Student Report");
            title.Format.Font.Size = 18;
            title.Format.Font.Bold = true;
            title.Format.SpaceAfter = "1cm";
            title.Format.Alignment = ParagraphAlignment.Center;

            // 4. Student details
            section.AddParagraph("Name: Kaviya");
            section.AddParagraph("Roll No: 101");
            section.AddParagraph("Date: " + DateTime.Now.ToString("dd-MM-yyyy"));
            section.AddParagraph("\n");

            // 5. Create table
            Table table = section.AddTable();
            table.Borders.Width = 0.75;

            table.AddColumn("5cm");
            table.AddColumn("3cm");

            // Header row
            Row header = table.AddRow();
            header.Shading.Color = Colors.LightGray;
            header.Cells[0].AddParagraph("Subject");
            header.Cells[1].AddParagraph("Marks");

            // Data rows
            AddRow(table, "Maths", "85");
            AddRow(table, "Science", "90");
            AddRow(table, "English", "88");

            // 6. Footer
            Paragraph footer = section.Footers.Primary.AddParagraph("Generated by Server");
            footer.Format.Alignment = ParagraphAlignment.Center;
            footer.Format.Font.Size = 9;

            // 7. Render PDF
            PdfDocumentRenderer renderer = new PdfDocumentRenderer();
            renderer.Document = document;
            renderer.RenderDocument();

            using MemoryStream stream = new MemoryStream();
            renderer.PdfDocument.Save(stream, false);
            return stream.ToArray();
        }

        private void AddRow(Table table, string subject, string marks)
        {
            Row row = table.AddRow();
            row.Cells[0].AddParagraph(subject);
            row.Cells[1].AddParagraph(marks);
        }
    }
}