name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore learningprojectserver.sln

      - name: Build
        run: dotnet build learningprojectserver.sln --no-restore

      - name: Run tests
        run: dotnet test learningprojectserver.sln --no-build

      - name: Publish application
        run: dotnet publish learningprojectserver.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: learningprojectserver
          path: ./publish